version: 2.1
executors:
  ci-executor:
    docker:
      - image: githubtraining/ci-custom:latest
jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
          
      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler

      - run:
          name: notify build is finished
          command: echo "The build is finished!"
          
  testlinks:
    executor: ci-executor
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler

      - run:
          name: notify build is finished
          command: echo "The build is finished!"

      - run:
          name: run html proofer
          command: bundle exec htmlproofer ./_site --check-html

      - run:
          name: notify test is finished
          command: echo "The test is completed!"

workflows:
  version: 2.1

  build_and_test:
    jobs:
      - build
      - testlinks:
          requires:
            - build
