version: 2.1
executors:
  ci-executor:
    docker:
      - image: githubtraining/ci-custom:latest
jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
          
      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler

      - run:
          name: notify build is finished
          command: echo "The build is finished!"
